# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Conan package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        compiler_runtime: [MD, MDd, MT, MTd]
        arch: [x86, x86_64]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        choco install --no-progress -r cmake --installargs 'ADD_CMAKE_TO_PATH=System'
        python -m pip install --upgrade pip
        pip install conan
    - name: Build Conan package
      run: |
        conan profile new --detect --force default
        conan profile update settings.arch=${{ matrix.arch }} default
        conan profile update settings.compiler.runtime=${{ matrix.compiler_runtime }} default
        conan remote add -f bincrafters https://api.bintray.com/conan/bincrafters/public-conan
        conan remote add -f gamepad64-public https://api.bintray.com/conan/gamepad64/public-conan
        conan create --build missing --build cascade . gamepad64/stable
    - name: Upload package to Bintray
      run: |
        conan upload winsparkle/0.6.0@gamepad64/stable -r gamepad64-public --all
